Oops! Assertion failed

The following assertion was not satisfied
  assert {'a':1} is False, error()

Assertion values
  assert {'a':1} is False, error()
         ^ is = {'a': 1}
  assert {'a':1} is False, error()
                 ^ is = False
  assert {'a':1} is False, error()
  ^ is False