Oops! Assertion failed

The following assertion was not satisfied
  assert 1 * 3 is False, error()

Assertion values
  assert 1 * 3 is False, error()
           ^ is = 3
  assert 1 * 3 is False, error()
               ^ is = False
  assert 1 * 3 is False, error()
  ^ is False

Where
  File 'tests/tests.py', line 176 in 'run'

168|                      with raises(AssertionError) as e:
169|                          assert 1 - 3 is False, error()
170|                      test.note(e.exception)
171|                      with this() as that:
172|                          assert that(snapshot(e.exception, "binary-ops-sub", encoder=str)), error()
173|              
174|                  with subsuite.test("mul") as test:
175|                      with raises(AssertionError) as e:
176|>                         assert 1 * 3 is False, error()
177|                      test.note(e.exception)
178|                      with this() as that:
179|                          assert that(snapshot(e.exception, "binary-ops-mul", encoder=str)), error()
