Oops! Assertion failed

The following assertion was not satisfied
  assert 1 < 1, error()

Assertion values
  assert 1 < 1, error()
           ^ is = False
  assert 1 < 1, error()
  ^ is False

Where
  File 'tests/tests.py', line 297 in 'run'

289|                      with raises(AssertionError) as e:
290|                          assert 1 != 1, error()
291|                      test.note(e.exception)
292|                      with this() as that:
293|                          assert that(snapshot(e.exception, "compare-ops-ne", encoder=str)), error()
294|                  
295|                  with subsuite.test("lt") as test:
296|                      with raises(AssertionError) as e:
297|>                         assert 1 < 1, error()
298|                      test.note(e.exception)
299|                      with this() as that:
300|                          assert that(snapshot(e.exception, "compare-ops-lt", encoder=str)), error()
