Oops! Assertion failed

The following assertion was not satisfied
  assert 1 is not 1, error()

Assertion values
  assert 1 is not 1, error()
           ^ is = False
  assert 1 is not 1, error()
  ^ is False

Where
  File 'tests/tests.py', line 332 in 'run'

324|                      with raises(AssertionError) as e:
325|                          assert 1 is 2, error()
326|                      test.note(e.exception)
327|                      with this() as that:
328|                          assert that(snapshot(e.exception, "compare-ops-is", encoder=str)), error()
329|                  
330|                  with subsuite.test("is not") as test:
331|                      with raises(AssertionError) as e:
332|>                         assert 1 is not 1, error()
333|                      test.note(e.exception)
334|                      with this() as that:
335|                          assert that(snapshot(e.exception, "compare-ops-is-not", encoder=str)), error()
