Oops! Assertion failed

The following assertion was not satisfied
  assert foo(x=1,y=2) is False, error()

Assertion values
  assert foo(x=1,y=2) is False, error()
         ^ is = {'x': 1, 'y': 2}
  assert foo(x=1,y=2) is False, error()
                      ^ is = False
  assert foo(x=1,y=2) is False, error()
  ^ is False

Where
  File 'tests/tests.py', line 109 in 'run'

101|  
102|                  with subsuite.test("**kwargs") as test:
103|                      vs = []
104|                      def foo(**x):
105|                          test.note(x)
106|                          vs.append(x)
107|                          return x
108|                      with raises(AssertionError) as e:
109|>                         assert foo(x=1,y=2) is False, error()
110|                      test.note(e.exception)
111|                      with test.test("assert **kwargs are the same"):
112|                          assert vs[0] == vs[1]
