Oops! Assertion failed

The following assertion was not satisfied
  assert 1 and 0, error()

Assertion values
  assert 1 and 0, error()
           ^ is = 0
  assert 1 and 0, error()
  ^ is False

Where
  File 'tests/tests.py', line 133 in 'run'

125|                      with test.test("assert args, *args, **kwargs are the same"):
126|                          assert vs[0] == vs[1]
127|                      with this() as that:
128|                          assert that(snapshot(e.exception, "func-args_*args_**kwargs", encoder=str)), error()
129|  
130|              with suite.test("boolean ops") as subsuite:
131|                  with subsuite.test("and") as test:
132|                      with raises(AssertionError) as e:
133|>                         assert 1 and 0, error()
134|                      test.note(e.exception)
135|                      with test.test("assert exception snapshot"), this() as that:
136|                          assert that(snapshot(e.exception, "and", encoder=str)), error()
